"""Core routing, capability gating, risk policy, and failure taxonomy."""

from openroutiq.router.capabilities import (
    CapabilityGate,
    CapabilityGateResult,
    CapabilityRequirements,
)
from openroutiq.router.core import (
    TASKS,
    CatalogError,
    CandidateScore,
    ChanceConstraint,
    Constraints,
    ContextAnalysis,
    ExcludedModel,
    ModelProfile,
    NoEligibleModelError,
    OpenRoutiQError,
    OutcomeEstimate,
    OutcomeForecast,
    OutcomeScenario,
    OutcomeStore,
    RiskPolicy,
    RouteContext,
    RouteDecision,
    Router,
    TaskClassifier,
    TaskPrediction,
    Weights,
    analyze_context,
    classify_task,
    local_sentence_embedder,
)
from openroutiq.router.failures import (
    FailureType,
    classify_failure,
    exception_status_code,
    normalize_failure_type,
)

__all__ = [
    "TASKS",
    "CatalogError",
    "CandidateScore",
    "CapabilityGate",
    "CapabilityGateResult",
    "CapabilityRequirements",
    "ChanceConstraint",
    "Constraints",
    "ContextAnalysis",
    "ExcludedModel",
    "FailureType",
    "ModelProfile",
    "NoEligibleModelError",
    "OpenRoutiQError",
    "OutcomeEstimate",
    "OutcomeForecast",
    "OutcomeScenario",
    "OutcomeStore",
    "RiskPolicy",
    "RouteContext",
    "RouteDecision",
    "Router",
    "TaskClassifier",
    "TaskPrediction",
    "Weights",
    "analyze_context",
    "classify_failure",
    "classify_task",
    "exception_status_code",
    "local_sentence_embedder",
    "normalize_failure_type",
]
